name: upload-encrypted-artifact
description: |
  This action creates an encrypted artifact.

  This action archives the provided paths into a file named `archive.tar`, encrypts it producing `archive.tar.age`, and uploads the encrypted file as an artifact.
  - Encryption tool: age (https://age-encryption.org)
  - Mode: recipient public key (X25519)

  Important:
  - Provide an age recipient public key (age1...) via the `recipient` input.
  - Use the matching `download-encrypted-artifact` action with the corresponding private identity key to decrypt and extract.

author: eidp
branding:
  icon: lock
  color: purple
inputs:
  directory:
    description: >
      Directory to run the action in. Defaults to the current working directory.
      If provided, the action will change to this directory before creating the archive.
      This is where the archive will be created and encrypted.
    required: false
    default: ''
  paths:
    description: >
      Space-separated list of files/directories to include in the archive. Globs are supported by the shell.
    required: true
  recipient:
    description: age recipient public key (starts with age1...).
    required: true
  artifact_name:
    description: Name of the artifact to upload.
    required: false
    default: encrypted-artifact
runs:
  using: composite
  steps:
  - name: Setup age
    uses: alessiodionisi/setup-age-action@82b9aea163ade7fe23441552a514cf666b214077 # v1.3.0

  - id: bundle-and-encrypt
    shell: bash
    run: |
      set -euo pipefail
      : "${{ inputs.paths }}"
      : "${{ inputs.recipient }}"

      if [ -z "${{ inputs.directory }}" ]; then
          WORKDIR="$(pwd)"
      else
          WORKDIR="${{ inputs.directory }}"
      fi
      cd "$WORKDIR"
      
      # Create archive.tar
      rm -f archive.tar archive.tar.age
      # shellcheck disable=SC2086
      read -r -a PATHS_ARRAY <<< "${{ inputs.paths }}"
      tar --exclude=archive.tar --exclude=archive.tar.age -cf archive.tar "${PATHS_ARRAY[@]}"

      # Encrypt archive.tar -> archive.tar.age using age recipient key
      age -r "${{ inputs.recipient }}" -o archive.tar.age archive.tar

      echo "Created and encrypted archive: $(pwd)/archive.tar.age"

  - name: Upload encrypted archive artifact
    uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
    with:
      name: ${{ inputs.artifact_name }}
      path: archive.tar.age
      if-no-files-found: error
outputs: {}
