name: apply
description: |
  Downloads a Terraform plan artifact and applies it.

  This action is designed to be used in a two-job apply workflow where:
  1. The `plan-for-apply` action runs in the first job to create and upload a plan
  2. This action runs in a second job (with environment approval) to apply the plan

  The second job can use GitHub's `environment` feature for approval gates
  and `concurrency` for preventing parallel applies.

  AWS credentials should be set as environment variables by the calling workflow.

author: eidp
branding:
  icon: play
  color: green

inputs:
  directory:
    description: >
      Path to the directory containing Terraform configuration.
      Defaults to ./terraform.
    required: false
    default: ./terraform
  extra_args:
    description: >
      Extra arguments to pass to the 'terraform apply' command.
      Useful for (dynamically) injecting variable files or flags.
    required: false
    default: ''
  extra_init_args:
    description: >
      Extra arguments to pass to the 'terraform init' command.
    required: false
    default: -lockfile=readonly
  terraform_version:
    description: >
      The version of Terraform to install and use.
    required: false
    default: '1.14.0'
  encrypted_artifact_name:
    description: >
      Name of the encrypted artifact to download. The artifact must contain
      a single file named `archive.tar.age` created by the upload-encrypted-artifact action.
    required: false
    default: ''
  artifact_identity:
    description: >
      age identity (private key) used to decrypt the encrypted artifact
      (full contents starting with '# created:' and containing 'AGE-SECRET-KEY-').
      Use the matching recipient public key when uploading.
    required: false
    default: ''
  debug:
    description: >
      Enable debug mode for more verbose logging. Defaults to false.
    required: false
    default: 'false'
  command_wrapper:
    description: >
      Optional command to wrap terraform commands with.
      Useful for credential injection tools like 1Password CLI (op run)
      or AWS Vault (aws-vault exec profile). Commands are executed as
      `[your_command] -- terraform [operation]`.
    required: false
    default: ''
  plan_artifact_name:
    description: >
      Name of the plan artifact to download. This should be the
      `plan_artifact_name` output from the `plan-for-apply` action.
    required: true

outputs:
  apply_outcome:
    description: |
      The outcome of the Terraform apply step (success or failure).
    value: ${{ steps.apply.outcome }}
  apply_output:
    description: |
      The output of the Terraform apply command.
    value: ${{ steps.apply.outputs.stdout }}

runs:
  using: composite
  steps:
  - name: Checkout Repo
    uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

  - name: Download encrypted artifact
    if: ${{ inputs.encrypted_artifact_name != '' }}
    uses: eidp/actions-terraform/download-encrypted-artifact@a9e5ccf7cf0dabd583d76bacdbc10e438b291b81 # v1.3.0
    with:
      artifact_name: ${{ inputs.encrypted_artifact_name }}
      identity: ${{ inputs.artifact_identity }}
      out_dir: './'

  - name: Setup Node
    uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
    with:
      node-version: '20.x'

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.8.2
    with:
      terraform_version: ${{ inputs.terraform_version }}

  - name: Terraform Init
    id: init
    shell: bash
    working-directory: ${{ inputs.directory }}
    run: |
      if [ -n "${{ inputs.command_wrapper }}" ]; then
        ${{ inputs.command_wrapper }} -- terraform init ${{ inputs.extra_init_args }} -input=false
      else
        terraform init ${{ inputs.extra_init_args }} -input=false
      fi

  - name: Download plan artifact
    uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
    with:
      name: ${{ inputs.plan_artifact_name }}
      path: ${{ inputs.directory }}

  - name: Terraform Apply
    id: apply
    shell: bash
    working-directory: ${{ inputs.directory }}
    run: |
      set -o pipefail
      if [ "${{ inputs.debug }}" = "true" ]; then
        export TF_LOG=TRACE
        export TF_LOG_PATH=./terraform.log
      fi

      if [ -n "${{ inputs.command_wrapper }}" ]; then
        ${{ inputs.command_wrapper }} -- terraform apply ${{ inputs.extra_args }} -auto-approve -input=false -no-color tfplan || APPLY_EXIT_CODE=$?
      else
        terraform apply ${{ inputs.extra_args }} -auto-approve -input=false -no-color tfplan || APPLY_EXIT_CODE=$?
      fi

      if [ -f ./terraform.log ]; then
        echo "----- Terraform Debug Log -----"
        cat ./terraform.log
      fi

      exit ${APPLY_EXIT_CODE:-0}
