name: download-encrypted-artifact
description: |
  Downloads an encrypted artifact file, decrypts it and extract its contents.

  This action downloads an artifact containing `archive.zip.bin`, decrypts it to `archive.zip` and unzips into the target directory.
  - Cipher: OpenSSL symmetric cipher (default: aes-256-cbc)
  - KDF: pbkdf2 with salt (OpenSSL default for `-pbkdf2 -salt`)

author: eidp
branding:
  icon: unlock
  color: green
inputs:
  artifact_name:
    description: Name of the artifact to download that contains `archive.zip.bin`.
    required: false
    default: encrypted-artifact
  encrypted_file:
    description: Path to the encrypted archive file (archive.zip.bin). If not provided, defaults to `${download_path}/archive.zip.bin` when an artifact is downloaded.
    required: false
    default: ''
  key:
    description: Passphrase used for encryption/decryption (store as a secret).
    required: true
  out_dir:
    description: Directory to extract the decrypted archive into (defaults to current working directory).
    required: false
    default: .
  cipher:
    description: OpenSSL cipher used (default aes-256-cbc).
    required: false
  cleanup:
    description: Whether to remove archive.zip and archive.zip.bin after extraction (true/false, default true).
    required: false
    default: 'true'
runs:
  using: composite
  steps:
  - name: Download encrypted archive artifact
    uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
    with:
      name: ${{ inputs.artifact_name }}

  - id: decrypt-and-unzip
    shell: bash
    run: |
      set -euo pipefail
      KEY="${{ inputs.key }}"; OUT_DIR="${{ inputs.out_dir }}"
      CIPHER="${{ inputs.cipher }}"; if [ -z "${CIPHER}" ]; then CIPHER=aes-256-cbc; fi
      CLEANUP="${{ inputs.cleanup }}";
      ENC_INPUT="archive.zip.bin"
      
      if [ ! -f "$ENC_INPUT" ]; then
        echo "Encrypted file not found: $ENC_INPUT" >&2
        exit 1
      fi
      
      mkdir -p "$OUT_DIR"
      ARCHIVE_ZIP="$OUT_DIR/archive.zip"
      
      # Decrypt archive.zip.bin -> archive.zip
      openssl enc -"$CIPHER" -d -pbkdf2 -pass pass:"$KEY" -in "$ENC_INPUT" -out "$ARCHIVE_ZIP"
      
      # Unzip into OUT_DIR
      unzip -o "$ARCHIVE_ZIP" -d "$OUT_DIR"
      
      if [ "${CLEANUP}" = "true" ]; then
        rm -f "$ARCHIVE_ZIP" "$ENC_INPUT"
      fi
      
      echo "Decrypted and extracted archive to: $OUT_DIR"
outputs: {}
