name: common

on:
  pull_request:
    branches:
      - main

jobs:
  common:
    uses: eidp/actions-common/.github/workflows/common.yml@217646e29a87d3a4f92590c3186832354a9418d2 # v1.4.1
    with:
      runs-on: kubernetes-runner
    permissions:
      pull-requests: write
      issues: write
