name: common

on:
  pull_request:
    branches:
      - main

jobs:
  common:
    uses: eidp/actions-common/.github/workflows/common.yml@11bfa25533857d8208bc809025b8589e10b1e61f # v1.4.2
    with:
      runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
