name: common

on:
  pull_request:
    branches:
      - main

jobs:
  common:
    uses: eidp/actions-common/.github/workflows/common.yml@d526a4979e76d11ce42031c782a0c907b1126e24 # v1.1.0
    with:
      runs-on: kubernetes-runner
    permissions:
      pull-requests: write
      issues: write
