name: common

on:
  pull_request:
    branches:
      - main

jobs:
  common:
    uses: eidp/actions-common/.github/workflows/common.yml@5432677a2aac2a4e09787d68519acb6617f65197 # v0.6.1
    with:
      runs-on: kubernetes-runner
    permissions:
      pull-requests: write
      issues: write
