name: release

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  update-major-version-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Update Major Version Tag
      id: update_major_version_tag
      uses: eidp/actions-common/update-major-version-tag@0878b81861674a916b2d0b8e66db5386cc95e066 # v0.6.2
