name: renovate
on:
  schedule:
  - cron: '8/30 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-slim
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Run Renovate
      uses: eidp/actions-common/renovate@217646e29a87d3a4f92590c3186832354a9418d2 # v1.4.1
      with:
        github-app-id: ${{ secrets.DEP_MANAGER_GITHUB_APP_ID }}
        github-app-pem: ${{ secrets.DEP_MANAGER_GITHUB_APP_PEM_FILE }}
        all-secrets: ${{ toJSON(secrets) }}
