name: renovate
on:
  schedule:
  - cron: '0/30 * * * *'
jobs:
  renovate:
    uses: eidp/actions-common/.github/workflows/renovate.yml@d526a4979e76d11ce42031c782a0c907b1126e24 # v1.1.0
    with:
      runs-on: dind-runner
    secrets:
      GITHUB_APP_ID: ${{ secrets.DEP_MANAGER_GITHUB_APP_ID }}
      GITHUB_APP_PEM_FILE: ${{ secrets.DEP_MANAGER_GITHUB_APP_PEM_FILE }}
