name: renovate
on:
  schedule:
  - cron: '8/30 * * * *'
jobs:
  renovate:
    runs-on: dind-runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Run Renovate
      uses: eidp/actions-common/renovate@fdaf77f825a926ddb1799dd31b05469da17fbd07 # v1.4.0
      with:
        github-app-id: ${{ secrets.DEP_MANAGER_GITHUB_APP_ID }}
        github-app-pem: ${{ secrets.DEP_MANAGER_GITHUB_APP_PEM_FILE }}
        all-secrets: ${{ toJSON(secrets) }}
