name: renovate
on:
  schedule:
  - cron: '0/30 * * * *'
jobs:
  renovate:
    uses: eidp/actions-common/.github/workflows/renovate.yml@42dc9e7586ba7a3b7aa74b2f235b220edf7fea44 # v0
    with:
      runs-on: dind-runner
      renovate-config-repo: renovate-config
    secrets:
      GITHUB_APP_ID: ${{ secrets.DEP_MANAGER_GITHUB_APP_ID }}
      GITHUB_APP_PEM_FILE: ${{ secrets.DEP_MANAGER_GITHUB_APP_PEM_FILE }}
